### PR TITLE
Add warning message for $user -> $__user migration.

### PR DESCRIPTION
**Pull request by gderber**
Keeping this one small, I know it works.

Also started thinking about it, it already applies to ut.sh and my upcoming new ports.

Not 100% sure about the wording of the message.  It works.

### CODE REVIEW

**Comment by Exarkuniv** [comment]
it should work , but i think we can also add to "update it through the setup GUI menu"
like it shows here
https://retropie.org.uk/docs/Updating-RetroPie/

of course word it better

**Comment by Exarkuniv** [comment]
Just going to merge. Since I can always edit the wording later

**Comment by gderber** [comment]
Sorry, the pace hasn't slowed down yet at work.

**Comment by Exarkuniv** [comment]
> Sorry, the pace hasn't slowed down yet at work.

it all good, i tested and it worked just fine on my end. i did 2 clean systems installs and each time the warning would come up before up and then be gone after. 

but it seems that for everyone else the warning was there no matter what.  even through they did the same thing as me. 
so we just need to look at the version else where. so in the revert pull i have the notes on where we should look. i just don't know how to do that.

**Pull request merged**
