### PR TITLE
Update $user -> $__user

### PR DESCRIPTION
**Pull request by gderber**
To piggy back off of https://www.github.com/RetroPie/RetroPie-Setup/pull/3951

This updates all
- $user:$user to $__user:$__group
- pi:pi to $__user:$__group
- /home/pi to $home

Re-enables x86 on a handful of scripts.

Note: This is still a WIP, I wanted you to be aware of it.

### CODE REVIEW

**Comment by gderber** [comment]
I understand that.  I've been trying to think of a decent solution.

I know as is, without the change some of those scripts provide really bad ownership settings (for examples the ones that do 'chown pi:pi ...' not using the variables at all.

I'm not really sure how to check that the person is using a more recent version of RP.  Maybe something like

if $(git log --format=format:%H | grep 18c2b43000ec54d74ba016e0b8de654122377dba); then ..

but even then, do we really want to add that check in every script, and if so for how long.  Maybe something in the update script or install script, that if that hash is not in the results then abort with a message saying RP needs an update before continuing?

**Comment by Exarkuniv** [comment]
very cool, again thanks 

as for how long, until there is a official release from RP. i would think. since at that point it will have this change already built in.

**Comment by gderber** [comment]
For a variety of reasons, this is growing rapidly in size.

I have only tested a handful of scripts so far, and I am running into build issues that are completely unrelated to my changes.

For example:
lr-boom3 fails to build because of a missing dependency.

Did not find needed dependencies: libjpeg-turbo8-dev libcurl4-openssl-dev. Trying to install them now. Ign:1 http://linux.dropbox.com/debian bookworm InRelease Hit:2 http://linux.dropbox.com/debian bookworm Release Hit:3 http://deb.debian.org/debian bookworm InRelease Hit:5 http://deb.debian.org/debian-security bookworm-security InRelease Hit:6 http://deb.debian.org/debian bookworm-updates InRelease Hit:7 http://deb.debian.org/debian bookworm-backports InRelease Hit:8 https://updates.signal.org/desktop/apt xenial InRelease Hit:9 https://repo.steampowered.com/steam stable InRelease Hit:10 https://download.opensuse.org/repositories/home:/strycore/Debian_12 ./ InRelease Hit:11 https://www.deb-multimedia.org bookworm InRelease Hit:12 https://www.deb-multimedia.org bookworm-backports InRelease Reading package lists... Reading package lists... Building dependency tree... Reading state information... Package libjpeg-turbo8-dev is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source E: Package 'libjpeg-turbo8-dev' has no installation candidate Could not install package(s): libjpeg-turbo8-dev libcurl4-openssl-dev. 

Changing the dependency from libjpeg-turbo8-dev to libjpeg-dev fixed the problem.

Similar issue with the rott* scripts. The rely on libfluidsynth1, which has been replaced by libfluidsynth2 on bullseye and lib*synth3 in bookworm.

Also having to add in a bunch of x86 to the flags.

Because of that I am seriously considering ditching this as is and submitting individual patches by script.

**Comment by gderber** [comment]
Splitting this up does have the benefit of reduced potential for conflicts during the time needed to work out the various issues while transitioning. 

It does drag out the transition for the end users.

**Comment by Exarkuniv** [comment]
Yeah. There is a bunch of work that's needed. This is going to be tricky. Since we still need to make sure these work on 32bit And 64bit. Until RetroPie switchs over to bookworm completely.

So going one by one might be better. 

Or at least do the transition in smaller batches. 
Whichever works I'm good with.

I'm working on getting the 2 legend of Zelda ports working. So I have not done much else

**Pull request closed without merging**
