### PR TITLE
Enhance rtcw installer

### PR DESCRIPTION
**Pull request by gderber**
- Add capability to build for x86_64 machines
- Fixes bug caused hard coded home by changing '/home/pi' to $home
- Clean up whitespace and follow RetroPie shell style guide

This should correct _arch_iortcw not found  I had replaced that previously, but it didn't look like it took for you, based on your last comment.

### CODE REVIEW

**Comment by Exarkuniv** [comment]
i get this at the end


```
= = = = = = = = = = = = = = = = = = = = =
Configuring 'rtcw' : RTCW - IORTCW source port of Return to Castle Wolfenstein.
= = = = = = = = = = = = = = = = = = = = =

rm: cannot remove '/home/pi/RetroPie/roms/ports/rtcw/vm': No such file or directory
/home/pi/RetroPie-Setup
```

**Comment by Exarkuniv** [comment]
im not sure. i have never had a issue with it before. and i just installed it with the old script yesterday 

i think rm command will just run no matter if a file is there or not. 
i just tested it and it just runs. so i think it checking for a file is not needed, but thats me

**Comment by Exarkuniv** [comment]
i never had a issue before with the old script, but it was made only for the Pi. so i can see it not having a issue

**Comment by gderber** [comment]
Yes, the architecture for that line should not have made any difference.

I changed that line from:
"rm -R /home/pi/RetroPie/roms/ports/rtcw/vm"
to
"rm -R $home/RetroPie/roms/ports/rtcw/vm"

so like I said, I am surprised that line hadn't failed previously for people.  $home is the variable RetroPie uses for the users home directory.

**Comment by Exarkuniv** [comment]
the script works just fine for me. 
though the ``vm`` folder is still in the ``rtcw`` folder.

**Comment by gderber** [comment]
It's supposed to be.  Basically, the 'rm' line is so that when recompiling, the new version gets installed.

**Pull request merged**
