### PR TITLE
Feature/openjkdf2

### PR DESCRIPTION
**Pull request by gderber**
Not sure how, my github branch and my local branch diverged, and trying to fix that messed up the pull request.

Really furstrating in than I hadn't touched the github branch until I tried to push my changes today.

### CODE REVIEW

**Comment by gderber** [comment]
Sorry about the repost of #139 

I thin my latest commit might fix a problem for you.

**Comment by Exarkuniv** [comment]
```
mkdir -p $build_dir
        cd $build_dir

        cmake .. --toolchain ../cmake_modules/linux_32_toolchain.cmake
        make -j10
```
this does not work at all. when i run it
```
CMake Error: Unknown argument --toolchain
CMake Error: Run 'cmake --help' for all supported options.
make: *** No targets specified and no makefile found.  Stop.
```
the only thing that works is building it with 64bit and it does build successfully

FYI. I only run/test the current build from RetroPie, So its 32bit

**Comment by gderber** [comment]
Okay, definitely related to 64bit build vs 32bit build.  What did you change to force a different cmake build?  The --toolchain switch was added to cmake at some point.  I need to modify the script to use the correct cmake version.

**Comment by Exarkuniv** [comment]
thats the think i dont know what version --toolchain was added. i have 3.20.3 installed other wise the 64bit would not build either. 
and --toolchain is still not working. im very confused

**Comment by Exarkuniv** [comment]
this is what i used to install 3.20.3

```
mkdir ~/temp
cd ~/temp
wget https://github.com/Kitware/CMake/releases/download/v3.20.3/cmake-3.20.3.tar.gz
tar -xzvf cmake-3.20.3.tar.gz
cd cmake-3.20.3

./bootstrap
make -j$(nproc)
sudo make install
```

**Comment by gderber** [comment]
I know --toolchain exists for 3.25.2 (since that is what I have).

Looking through the git log, '--toolchain' was added in 3.20.2  So your version should work.

I am trying to think of a way to force the script to create a temporary cmake that it uses, and gets removed upon completion.

Do you mind attempting an install of cmake 3.25.2.  It's occured to me there is no need to modify the script if you can't get cmake working.

**Comment by Exarkuniv** [comment]
sure. i can give it a shot and see what happens

**Comment by Exarkuniv** [comment]
ok i have cmake 3.25.2 install, i verified the version with ``cmake --version`` and it is correct.
so i ran the script and...

```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/local/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pi/RetroPie-Setup/tmp/build/openjkdf2/build/CMakeFiles/CMakeScratch/TryCompile-tqUfAi

    Run Build Command(s):/usr/bin/make -f Makefile cmTC_3e5da/fast && /usr/bin/make  -f CMakeFiles/cmTC_3e5da.dir/build.make CMakeFiles/cmTC_3e5da.dir/build
    make[1]: Entering directory '/home/pi/RetroPie-Setup/tmp/build/openjkdf2/build/CMakeFiles/CMakeScratch/TryCompile-tqUfAi'
    Building C object CMakeFiles/cmTC_3e5da.dir/testCCompiler.c.o
    /usr/bin/cc   -m32  -o CMakeFiles/cmTC_3e5da.dir/testCCompiler.c.o -c /home/pi/RetroPie-Setup/tmp/build/openjkdf2/build/CMakeFiles/CMakeScratch/TryCompile-tqUfAi/testCCompiler.c
    cc: error: unrecognized command line option ‘-m32’; did you mean ‘-mbe32’?
    make[1]: *** [CMakeFiles/cmTC_3e5da.dir/build.make:78: CMakeFiles/cmTC_3e5da.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/home/pi/RetroPie-Setup/tmp/build/openjkdf2/build/CMakeFiles/CMakeScratch/TryCompile-tqUfAi'
    make: *** [Makefile:127: cmTC_3e5da/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:21 (project)


-- Configuring incomplete, errors occurred!
See also "/home/pi/RetroPie-Setup/tmp/build/openjkdf2/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/RetroPie-Setup/tmp/build/openjkdf2/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
Could not successfully build openjkdf2 - OpenJKDF2 is a function-by-function reimplementation of Dark Forces 2. (build/openjkdf2 not found).
/home/pi/RetroPie-Setup
Errors:
Could not successfully build openjkdf2 - OpenJKDF2 is a function-by-function reimplementation of Dark Forces 2. (build/openjkdf2 not found).
```
no idea on this one

**Comment by gderber** [comment]
I was about ready to through in the towel on getting this working on an rpi, or at least take a break.  I have one last idea to try.

His instructions only mention using clang for building on an x86_64.  That said, you seemed to have some previous success with clang on an rpi.  So lets try using clang for all builds.

If this doesn't work, I'm very close to throwing in the towel, marking it as x86 only and maybe creating an issue for feature request enable on rpi with at "Help Wanted" tag.

**Comment by Exarkuniv** [comment]
ok im going to give that a shot. 

i built it again with 64bit and been trying to get it to run. 

it does try since i get ``Recreating SDL2 Window!`` when i run it with xinit. im even trying it with matchbox-window-manager
but then i get a window to come up on my screen 
```
failed to initialize sdl opengl content 
could not create GL context: glxbadfbconfig
```

thats as far as i can get it

**Comment by Exarkuniv** [comment]
so i tried to get it to build with the 32bit and i get this
```
-- FALSE
-- Targeting Linux 32-bit
-- Using the multi-header code from /home/pi/RetroPie-Setup/tmp/build/openjkdf2/3rdparty/json/include/
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
CMake Error at /usr/local/share/cmake-3.25/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.25/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:561 (pkg_check_modules)
```
i checked and we to have libgtk-3-dev installed

**Comment by Exarkuniv** [comment]
im fine with this just being a x86 script right now. 

so clean up what you need to

**Comment by gderber** [comment]
Let's give it a couple days.

I have 3 machines.  My daily driver is debian testing.  I also have an ubuntu 22.04 lts (also x86_64) for mythtv.  This builds and plays beautifully on my debian system.

You're problems got me thinking, and I decided to test on ubuntu.  It fails as well.

Ubuntu 22.04:
cmake is 3.22.1
Clang is 14.0.0

Debian testing:
cmake is 3.25.1
clang 14.0.6

I would have expected it to fail on the debian system before the ubuntu system, not the other way around.

I've submitted an upstream bug.  The solution may help out with building on a rpi.

**Comment by Exarkuniv** [comment]
Sounds good, thanks for taking a crack at this.

**Comment by gderber** [comment]
So I found a fix, for me.  On debian 12 and Ubuntu 22, I neded to add "libstdc++12-dev" to the list of dependencies.

The problem is buster doesn't have libstdc++12-dev.  It's version is libstdc++8-dev.

Based on what you've done, I would not expect installing libstdc++8-dev to fix your problem.

**Comment by gderber** [comment]
I've gone ahead and marked it x86_64 only for now.  Probably worth trying on a rpi once bullseye is out.

**Pull request merged**
