### PR TITLE
Feature/rtcw x86

### PR DESCRIPTION
**Pull request by gderber**
The current rtcw script will fail on an x86 machine.  This patch fixes that problem.

### CODE REVIEW

**Comment by gderber** [comment]
It also fixes a bug caused by hard coding $HOME to /home/pi which will only work if the retropie username is 'pi'.

**Comment by Exarkuniv** [comment]
What's with all the spaces.

And will it work on the pie since you change it to arch?

**Comment by Exarkuniv** [comment]
Just so you know. You are on your own with testing these on a PC. Since I don't have one

Im only concerned about them running on a Pi

**Comment by gderber** [comment]
Yes, it should still work on a rpi.

```
function _arch_rtcw() {
    # exact parsing from Makefile
    echo "$(uname -m | sed -e 's/i.86/x86/' | sed -e 's/^arm.*/arm/')"
}
```
Returns the architecture of the build.  So on x86_64 it will return "x86_64" on an rpi, it should return "armv7l".  You'll notice it's what's used in openjk_ja, openjk_jo, and ioquake3 (which is where I got the idea from, literal copy and paste)

As for the spaces that is in keeping with the [RetroPie Style guide](https://github.com/RetroPie/RetroPie-Docs/blob/master/docs/Shell-Style-Guide.md#indentation) which says to use 4 spaces and no tabs.  It also says that the command should either be all on one line, or one pipeline per line.  Updated patch, removed some excess spaces.  Not sure why I ended up with that many spaces.

I'm fine with testing them an a PC.  I have to test them on a PC, since it's what I have.

**Comment by Exarkuniv** [comment]
nope didnt work

```
LD build/release-linux-arm/iowolfded.arm
LD build/release-linux-arm/iowolfmp.arm
LD build/release-linux-arm/main/cgame.mp.arm.so
LD build/release-linux-arm/main/qagame.mp.arm.so
LD build/release-linux-arm/main/ui.mp.arm.so
make[2]: Leaving directory '/home/pi/RetroPie-Setup/tmp/build/rtcw/MP'
make[1]: Leaving directory '/home/pi/RetroPie-Setup/tmp/build/rtcw/MP'
/home/pi/RetroPie-Setup
/home/pi/RetroPie-Setup/tmp/build/rtcw /home/pi/RetroPie-Setup
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
/home/pi/RetroPie-Setup/ext/test/scriptmodules/ports/rtcw.sh: line 116: _arch_iortcw: command not found
Could not successfully install RTCW - IORTCW source port of Return to Castle Wolfenstein. (/home/pi/RetroPie-Setup/tmp/build/rtcw/SP/build/release-linux-/iowolfsp. not found).
/home/pi/RetroPie-Setup
Errors:
Could not successfully install RTCW - IORTCW source port of Return to Castle Wolfenstein. (/home/pi/RetroPie-Setup/tmp/build/rtcw/SP/build/release-linux-/iowolfsp. not found).
```

**Comment by gderber** [comment]
Sorry! Closing this, my rebase failed and looks like caught your updates.  I'll resubmit.

**Comment by Exarkuniv** [comment]
> Not sure why I ended up with that many spaces.

ok least it was not me, lol. i was like dang, i missed something here. lol

**Comment by gderber** [comment]
Opened cleaned up pull request.  Something went horribly awry with this version.

**Pull request closed without merging**
