### PR TITLE
Majora's Mask Source Port Added

### PR DESCRIPTION
**Pull request by retropieuser**
Have created 2s2h.sh based on https://github.com/HarbourMasters/2ship2harkinian oddly I don't seem to have as many memory issues when building this compared to Ocarina, perhaps as it's a smaller game, who knows.

Anyway have a test and see if this works for you. You'll need the USA Majora's mask rom in your N64 directory (it can be the original N64 or the GC version I think)

### CODE REVIEW

**Comment by retropieuser** [comment]
@Exarkuniv do you know how to point the get source function to a specific pull request? 

https://github.com/HarbourMasters/2ship2harkinian/pull/701

I tested this lull request, it gives you a nice GUI when you hit back on the SDL controller which you can use to set configs and quit. As atm quitting requires a mouse and keyboard otherwise

**Comment by Exarkuniv** [comment]
I believe you are looking for this

At the top of the page it will have the user wants to do some to (this thing) from (the other thing)

You can click on the other thing since it's a link going to the original page.

So for the page you are looking for is this

https://github.com/Malkierian/2ship2harkinian/tree/modern-menu

**Comment by retropieuser** [comment]
Ah yes that makes sense. I might just wait till it gets merged properly but it does seem quite useful right now, but even without the gamepad menu you can exit with a keyboard or mouse so the game itself functions fine 

Does it build for you ok? Not sure why I found this possible when Ocarina tends to fail to build

**Comment by Exarkuniv** [comment]
sorry i have not tryed it
i have been working on getting my jetson nano system up and going first

**Comment by Exarkuniv** [comment]
ok i was able to get this up and going, but the game locks up my whole system right after the first company logo

since i have no idea on whats going on, here is my runcommand 
```
Parameters: 
Executing: /opt/retropie/ports/2s2h/2s2h.sh
[2024-09-10 23:43:04.820] [/home/pi/RetroPie-Setup/tmp/build/2s2h/libultraship/src/resource/archive/ArchiveManager.cpp:152] [info] Reading archive: /opt/retropie/ports/2s2h/./mm.o2r
[2024-09-10 23:43:04.963] [/home/pi/RetroPie-Setup/tmp/build/2s2h/libultraship/src/resource/archive/ArchiveManager.cpp:182] [info] Adding Archive /opt/retropie/ports/2s2h/./mm.o2r to Archive Manager
[2024-09-10 23:43:05.001] [/home/pi/RetroPie-Setup/tmp/build/2s2h/libultraship/src/resource/archive/ArchiveManager.cpp:152] [info] Reading archive: /opt/retropie/ports/2s2h/2ship.o2r
[2024-09-10 23:43:05.004] [/home/pi/RetroPie-Setup/tmp/build/2s2h/libultraship/src/resource/archive/O2rArchive.cpp:28] [trace] Failed to find file version in zip archive  /opt/retropie/ports/2s2h/2ship.o2r.
[2024-09-10 23:43:05.004] [/home/pi/RetroPie-Setup/tmp/build/2s2h/libultraship/src/resource/archive/ArchiveManager.cpp:182] [info] Adding Archive /opt/retropie/ports/2s2h/2ship.o2r to Archive Manager
[23:43:05.823] [os.cpp:27] [error] Failed add SDL game controller mappings from "./gamecontrollerdb.txt" (Invalid RWops)
[23:43:08.313] [z_demo.c:1581] [info] Cutscene_HandleConditionalTriggers: entrance: 7168, cutsceneIndex: 0xFFFA
[23:43:08.318] [GameInteractor.cpp:126] [debug] OnFlagSet: flagType: 1, flag: 6976
File Name scenes/nonmq/SPOT00/SPOT00_room_00
[23:43:08.318] [GameInteractor.cpp:126] [debug] OnFlagSet: flagType: 1, flag: 7040
[23:43:08.318] [GameInteractor.cpp:126] [debug] OnFlagSet: flagType: 1, flag: 7169
[23:43:08.318] [GameInteractor.cpp:126] [debug] OnFlagSet: flagType: 1, flag: 7170
[23:43:08.318] [GameInteractor.cpp:126] [debug] OnFlagSet: flagType: 1, flag: 7172
[23:43:08.318] [GameInteractor.cpp:135] [debug] OnFlagUnset: flagType: 1, flag: 6976
[23:43:08.318] [GameInteractor.cpp:135] [debug] OnFlagUnset: flagType: 1, flag: 7040
[23:43:08.318] [GameInteractor.cpp:135] [debug] OnFlagUnset: flagType: 1, flag: 7169
[23:43:08.318] [GameInteractor.cpp:135] [debug] OnFlagUnset: flagType: 1, flag: 7170
[23:43:08.318] [GameInteractor.cpp:135] [debug] OnFlagUnset: flagType: 1, flag: 7172
[23:43:08.318] [GameInteractor.cpp:46] [debug] OnRoomInit: sceneId: 8, roomNum: 0
[23:43:08.324] [ResourceLoader.cpp:81] [error] Failed to load resource: File not loaded
[23:43:08.349] [CrashHandler.cpp:72] [critical] Signal: 11
INVALID ACCESS TO STORAGE
Registers:
Traceback:
1 __kernel_rt_sigreturn (+0x0)
2 /lib/aarch64-linux-gnu/libc.so.6(+0x80a10) [0x7fb9830a10]
3 gsignal (+0x1C)
4 /lib/aarch64-linux-gnu/libSDL2-2.0.so.0(+0x10efe0) [0x7fb9fcefe0]
5 __kernel_rt_sigreturn (+0x0)
6 SOH::ResourceFactoryBinaryAnimationV0::ReadResource(std::shared_ptr<Ship::File>) (+0xB1C)
7 Ship::ResourceLoader::LoadResource(std::shared_ptr<Ship::File>) (+0x78)
8 Ship::ResourceManager::LoadResourceProcess(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::shared_ptr<Ship::ResourceInitData>) (+0x374)
9 BS::thread_pool::submit_task<std::_Bind<std::shared_ptr<Ship::IResource> (Ship::ResourceManager::*(Ship::ResourceManager*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::shared_ptr<Ship::ResourceInitData>))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::shared_ptr<Ship::ResourceInitData>)>, std::shared_ptr<Ship::IResource> >(std::_Bind<std::shared_ptr<Ship::IResource> (Ship::ResourceManager::*(Ship::ResourceManager*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::shared_ptr<Ship::ResourceInitData>))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::shared_ptr<Ship::ResourceInitData>)>&&, short)::{lambda()#1}::operator()() const (+0x7C)
10 BS::thread_pool::worker(unsigned int, std::function<void ()> const&) (+0x144)
11 /lib/aarch64-linux-gnu/libstdc++.so.6(+0xce9dc) [0x7fb9b0e9dc]
12 /lib/aarch64-linux-gnu/libc.so.6(+0x7ee58) [0x7fb982ee58]
13 /lib/aarch64-linux-gnu/libc.so.6(+0xe7f9c) [0x7fb9897f9c]

```

**Comment by Exarkuniv** [comment]
i got it to work at the last min
ill put in my fixes monday

**Pull request merged**
